dink95/TIKITAKA

- service/product/src/main/java/com/tiki/product/ProductApplication.java
- service/product/src/main/java/com/tiki/product/configuration/DBConfiguration.java
- service/product/src/main/java/com/tiki/product/controller/ProductController.java
- service/product/src/main/java/com/tiki/product/domain/BuylistDTO.java
- service/product/src/main/java/com/tiki/product/domain/CategoryDTO.java
- service/product/src/main/java/com/tiki/product/domain/ProductDTO.java
- service/product/src/main/java/com/tiki/product/mapper/BuylistMapper.java
- service/product/src/main/java/com/tiki/product/mapper/CategoryMapper.java
- service/product/src/main/java/com/tiki/product/mapper/ProductMapper.java
- service/product/src/main/java/com/tiki/product/service/BuylistService.java
- service/product/src/main/java/com/tiki/product/service/BuylistServiceImpl.java
- service/product/src/main/java/com/tiki/product/service/CategoryService.java
- service/product/src/main/java/com/tiki/product/service/CategoryServiceImpl.java
- service/product/src/main/java/com/tiki/product/service/ProductService.java
- service/product/src/main/java/com/tiki/product/service/ProductServiceImpl.java
- service/product/src/main/resources/application.properties
- service/product/src/main/resources/mappers/BuylistMapper.xml
- service/product/src/main/resources/mappers/CategoryMapper.xml
- service/product/src/main/resources/mappers/ProductMapper.xml
prod, buylist, category 기본 dto, service, mapper 추가
xml 카멜케이스 적용
> product 기본 기능 업데이트

- .gitignore
- .idea/compiler.xml
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
- service/member/src/main/java/com/tiki/member/domain/MemberDTO.java
- service/member/src/main/java/com/tiki/member/mapper/MemberMapper.java
- service/member/src/main/java/com/tiki/member/service/MemberService.java
- service/member/src/main/java/com/tiki/member/service/MemberServiceImp.java
- service/member/src/main/resources/mapper/MemberMapper.xml
member service에 해당 내용 추가
controller update
예정) client --> service 추가
> ID찾기, PWD 수정 및 확인 추가

- client/src/main/java/com/tiki/client/controller/MemberController.java
- client/src/main/java/com/tiki/client/service/MemberService.java
- client/src/main/resources/static/css/bootstrap.min.css
- client/src/main/resources/static/css/style.css
- client/src/main/resources/static/js/main.js
- client/src/main/resources/templates/common.html
- client/src/main/resources/templates/member/findpwd.html
- client/src/main/resources/templates/member/login.html
- client/src/main/resources/templates/member/signup.html
- client/src/main/resources/templates/member/updatepwd.html
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
- service/member/src/main/java/com/tiki/member/domain/MemberDTO.java
- service/member/src/main/resources/application.properties
- service/member/src/main/resources/mapper/MemberMapper.xml
관리자 로그인 화면, 아이디중복확인, 아이디 찾기 , 비번 찾기 , 비번 수정 추가
> 아이디 찾기, 비번찾기

- client/src/main/java/com/tiki/client/service/MemberService.java
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
> 클라이언트 service 수정

- service/product/src/main/java/com/tiki/product/controller/ProductController.java
- service/product/src/main/java/com/tiki/product/domain/ProductDTO.java
- service/product/src/main/java/com/tiki/product/mapper/ProductMapper.java
- service/product/src/main/java/com/tiki/product/service/BuylistServiceImpl.java
- service/product/src/main/java/com/tiki/product/service/CategoryServiceImpl.java
- service/product/src/main/java/com/tiki/product/service/ProductService.java
- service/product/src/main/java/com/tiki/product/service/ProductServiceImpl.java
- service/product/src/test/java/com/tiki/product/ProductApplicationTests.java
product controller 수정, service serviceImpl 오타 수정
> service/product 수정 및 추가

- client/src/main/java/com/tiki/client/controller/MemberController.java
- client/src/main/resources/templates/index.html
- client/src/main/resources/templates/member/findpwd.html
- client/src/main/resources/templates/member/updatepwd.html
updatepwd.html 다시 추가 ,
updatepwd페이지 url 직접 접근 막기 추가
> updatepwd다시 추가

- .gitignore
- .idea/compiler.xml
- client/src/main/java/com/tiki/client/service/MemberService.java
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
- service/member/src/main/java/com/tiki/member/mapper/MemberMapper.java
- service/member/src/main/java/com/tiki/member/service/MemberService.java
- service/member/src/main/java/com/tiki/member/service/MemberServiceImp.java
- service/member/src/main/resources/application.properties
- service/member/src/main/resources/mapper/MemberMapper.xml
- 추가정보/SQL문.sql
ID, PHONE, EMAIL 중복 CHECK 쿼리 추가
TABLE SQL 오류 수정
> SQL정보 수정 및 CHECK 기능 추가

- client/src/main/java/com/tiki/client/controller/MemberController.java
- client/src/main/resources/templates/member/signup.html
- service/member/src/main/resources/application.properties
> 이메일, 전화번호 중복 체크 기능 추가

- .idea/compiler.xml
- service/product/build.gradle
- service/product/src/main/java/com/tiki/product/controller/CategoryController.java
- service/product/src/main/java/com/tiki/product/controller/ProductController.java
- service/product/src/main/java/com/tiki/product/service/ProductService.java
- service/product/src/main/java/com/tiki/product/service/ProductServiceImpl.java
- service/product/src/main/resources/mappers/ProductMapper.xml
Product Controller
1. 전체 리스트 추가
2. 상품 등록 수정
3. 상품 삭제 추가
4. 다중 파일 업로드 (아직 미완성)
Category Controller 전체 추가
build.gradle
- file-upload dependencies 추가
> product / category controller 추가

- client/src/main/java/com/tiki/client/controller/ProductController.java
- client/src/main/java/com/tiki/client/domain/ProductDTO.java
- client/src/main/java/com/tiki/client/service/ProductService.java
- client/src/main/resources/templates/product/create.html
- gateway/src/main/java/com/tiki/gateway/config/GatewayConfiguration.java
- service/member/src/main/resources/application.properties
- service/product/src/main/java/com/tiki/product/controller/ProductController.java
- service/product/src/main/java/com/tiki/product/domain/InsertProdDTO.java
- service/product/src/main/java/com/tiki/product/domain/ProductDTO.java
- service/product/src/main/java/com/tiki/product/mapper/ProductMapper.java
- service/product/src/main/java/com/tiki/product/service/ProductService.java
- service/product/src/main/java/com/tiki/product/service/ProductServiceImpl.java
- service/product/src/main/resources/application.properties
- service/product/src/main/resources/mappers/ProductMapper.xml
- 추가정보/SQL문.sql
제품 -> service(product)에서 저장 
제품 img -> client단에서 prodNo/count.jpg로 저장 count는 이미지 수마다 증가
> 제품 저장 및 이미지 업로드

- service/member/src/main/java/com/tiki/member/domain/ComplainDTO.java
- service/member/src/main/java/com/tiki/member/mapper/ComplainMapper.java
- service/member/src/main/java/com/tiki/member/service/ComplainService.java
- service/member/src/main/java/com/tiki/member/service/ComplainServiceImp.java
- service/member/src/main/resources/mapper/BlackListMapper.xml
- service/member/src/main/resources/mapper/ComplainMapper.xml
> complain 추가

- client/src/main/java/com/tiki/client/service/ComplainService.java
- gateway/src/main/java/com/tiki/gateway/config/GatewayConfiguration.java
- service/member/src/main/java/com/tiki/member/controller/ComplainController.java
> 신고 게시판 client & service 컨트롤러 추가

- client/src/main/java/com/tiki/client/config/WebConfig.java
- client/src/main/java/com/tiki/client/controller/ComplainController.java
- client/src/main/java/com/tiki/client/controller/MemberController.java
- client/src/main/java/com/tiki/client/controller/ProductController.java
- client/src/main/java/com/tiki/client/domain/ComplainDTO.java
- client/src/main/resources/static/js/main.js
- client/src/main/resources/templates/common.html
- client/src/main/resources/templates/complain/index.html
- client/src/main/resources/templates/member/login.html
- client/src/main/resources/templates/product/create.html
- client/src/main/resources/templates/product/create_result.html
- client/src/main/resources/templates/product/detail.html
- client/src/main/resources/templates/product/list.html
- client/src/main/resources/templates/product/update.html
- service/member/src/main/java/com/tiki/member/domain/ComplainDTO.java
- 추가정보/SQL문.sql
- 추가정보/삽입.sql
> sql 추가, 최종 수정 전

- service/product/src/main/java/com/tiki/product/mapper/ProductMapper.java
- service/product/src/main/java/com/tiki/product/service/ProductServiceImpl.java
- service/product/src/main/resources/mappers/ProductMapper.xml
- service/product/src/test/java/com/tiki/product/ProductApplicationTests.java
> 물건 볼 때마다 조회수 증가

- .idea/compiler.xml
- service/member/build.gradle
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
- service/member/src/main/resources/application.properties
- service/product/src/main/java/com/tiki/product/controller/ProductController.java
- service/product/src/main/java/com/tiki/product/domain/ProductDTO.java
- service/product/src/main/java/com/tiki/product/mapper/ProductMapper.java
- service/product/src/main/java/com/tiki/product/service/ProductService.java
- service/product/src/main/java/com/tiki/product/service/ProductServiceImpl.java
- service/product/src/main/resources/application.properties
- service/product/src/main/resources/mappers/ProductMapper.xml
- service/product/src/test/java/com/tiki/product/ProductApplicationTests.java
- 추가정보/SQL문.sql
- 메일 인증
1) 메일 인증에 필요한 member/build.gradle, ./application.properties 코드 추가
2) 1)과 관련된 controller 코드 추가 (미완성)
- 판매 완료
1) prod table에 prod_finish column 추가 / 기본 상태는 'false' 이며, 판매자가 판매 완료 check 할 시 'true' 로 변경
2) 1) 로 인한 DTO 추가
3) 판매 완료 update service 추가
4) 3) 으로 인한 mapper, xml, serviceImpl 추가
5) selectProductList 사용할 시 판매 완료된 상품은 기본적으로 보이지 않게 변경
- 기타
기존 상품 검색(이름, 카테고리) 시 등록 날짜로 정렬이 안되는 사항 해결
> 메일인증, 판매완료 상세 설명 필수 확인

- client/src/main/java/com/tiki/client/controller/MemberController.java
- client/src/main/java/com/tiki/client/service/MemberService.java
- client/src/main/resources/templates/member/information/certify.html
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
- service/member/src/main/java/com/tiki/member/mapper/MemberMapper.java
- service/member/src/main/java/com/tiki/member/service/MemberService.java
- service/member/src/main/java/com/tiki/member/service/MemberServiceImp.java
- service/member/src/main/resources/mapper/MemberMapper.xml
> 이메일 인증 test (1)

- client/src/main/resources/templates/member/information/myinfo.html
> 이메일인증 test(2) 상품 이미지 경로 

- client/src/main/resources/templates/member/information/myinfo.html
> 내정보 페이지 수정

- client/src/main/java/com/tiki/client/service/MemberService.java
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
> role update 추가

- .idea/compiler.xml
- client/src/main/java/com/tiki/client/controller/ChattingController.java
- client/src/main/java/com/tiki/client/controller/MemberController.java
- client/src/main/java/com/tiki/client/domain/ChatDTO.java
- client/src/main/java/com/tiki/client/domain/ProductDTO.java
- client/src/main/java/com/tiki/client/service/ChatService.java
- client/src/main/resources/static/css/icon.css
- client/src/main/resources/static/css/style.css
- client/src/main/resources/static/js/main.js
- client/src/main/resources/templates/common.html
- client/src/main/resources/templates/member/chatting/chat.html
- client/src/main/resources/templates/member/chatting/room.html
- client/src/main/resources/templates/member/information/userInfo.html
- service/product/src/main/java/com/tiki/product/controller/ChatController.java
- service/product/src/main/java/com/tiki/product/controller/ProductController.java
- service/product/src/main/java/com/tiki/product/domain/ChatDTO.java
- service/product/src/main/java/com/tiki/product/domain/InsertProdDTO.java
- service/product/src/main/java/com/tiki/product/domain/ProductDTO.java
- service/product/src/main/java/com/tiki/product/mapper/ChatMapper.java
- service/product/src/main/java/com/tiki/product/service/ChatService.java
- service/product/src/main/java/com/tiki/product/service/ChatServiceImpl.java
- service/product/src/main/resources/mappers/ChatMapper.xml
> Kmg 210809

- client/src/main/java/com/tiki/client/controller/ChattingController.java
- client/src/main/java/com/tiki/client/service/ChatService.java
- client/src/main/resources/static/css/icon.css
- client/src/main/resources/static/css/style.css
- client/src/main/resources/static/js/main.js
- client/src/main/resources/templates/common.html
- client/src/main/resources/templates/complain/index.html
- client/src/main/resources/templates/index.html
- client/src/main/resources/templates/member/chatting/chat.html
- client/src/main/resources/templates/member/chatting/room.html
- client/src/main/resources/templates/member/information/myinfo.html
- client/src/main/resources/templates/member/login.html
- client/src/main/resources/templates/product/detail.html
- client/src/main/resources/templates/product/list.html
- service/product/src/main/java/com/tiki/product/controller/ChatController.java
- service/product/src/main/java/com/tiki/product/mapper/ChatMapper.java
- service/product/src/main/java/com/tiki/product/service/ChatService.java
- service/product/src/main/java/com/tiki/product/service/ChatServiceImpl.java
- service/product/src/main/resources/mappers/ChatMapper.xml
> Kmg 210816

- gateway/build.gradle
- gateway/src/main/java/com/tiki/gateway/Filter/AuthorizationHeaderFilter.java
- gateway/src/main/java/com/tiki/gateway/Filter/CustomFilter.java
- gateway/src/main/java/com/tiki/gateway/Filter/GlobalFilter.java
- gateway/src/main/resources/application.yml
- service/member/build.gradle
- service/member/src/main/java/com/tiki/member/MemberApplication.java
- service/member/src/main/java/com/tiki/member/configuration/AuthenticationFilter.java
- service/member/src/main/java/com/tiki/member/configuration/SpringSecurityConfiguration.java
- service/member/src/main/java/com/tiki/member/controller/MemberController.java
- service/member/src/main/java/com/tiki/member/service/MemberService.java
- service/member/src/main/java/com/tiki/member/service/MemberServiceImp.java
- service/member/src/main/resources/application.properties
gateway 인증 방식 jwt token발급 방식으로 추가
member login인 시, 발급하는 형식으로 제작
spring security의 login 시, token발급으로 하려 했으나, log를 통한 방식으로도 해답이 나오지 않아 우선 login API 호출 시로 변경
> gateway 및 member service변경
